apiVersion: virtualrouter.tmax.hypercloud.com/v1
kind: LoadBalancerRule
metadata:
  name: testloadbalancer
  namespace: virtualrouter
spec:
  rules:
  - loadBalancerIP: 192.168.9.133  # LB IP
    loadBalancerPort: 10000        # LB port
protocol: tcp		   # Protocol field
    backends:
    - backendIP: 10.10.10.1        # target1 IP
      backendPort: 20000           # target1 Port
      weight: 20                   #
      healthcheckMethod: icmp      # healthcheck-method: icmp
      healthcheckIP: 10.10.10.1    # need to specify the health-check target's IP
    - backendIP: 10.10.10.2        # target2 IP
      backendPort: 20000           # target1 Port
      weight: 30                   #
      healthcheckMethod: none      # No health-check for the target 2
    - backendIP: 10.10.10.3        # target3 IP
      backendPort: 20000           # target1 Port
      weight: 50                   #
      healthcheckMethod: tcp       # health-check: TCP handshake
      healthcheckIP: 10.10.10.3    # need to specify the health-check target's IP
      healthcheckPort: 20000	   # In case the health-check method is TCP, the port number should be specified
