/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	networkcontrollerv1 "github.com/tmax-cloud/virtualrouter/pkg/apis/networkcontroller/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLoadBalancerRules implements LoadBalancerRuleInterface
type FakeLoadBalancerRules struct {
	Fake *FakeTmaxV1
	ns   string
}

var loadbalancerrulesResource = schema.GroupVersionResource{Group: "tmax.hypercloud.com", Version: "v1", Resource: "loadbalancerrules"}

var loadbalancerrulesKind = schema.GroupVersionKind{Group: "tmax.hypercloud.com", Version: "v1", Kind: "LoadBalancerRule"}

// Get takes name of the loadBalancerRule, and returns the corresponding loadBalancerRule object, and an error if there is any.
func (c *FakeLoadBalancerRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *networkcontrollerv1.LoadBalancerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(loadbalancerrulesResource, c.ns, name), &networkcontrollerv1.LoadBalancerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.LoadBalancerRule), err
}

// List takes label and field selectors, and returns the list of LoadBalancerRules that match those selectors.
func (c *FakeLoadBalancerRules) List(ctx context.Context, opts v1.ListOptions) (result *networkcontrollerv1.LoadBalancerRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(loadbalancerrulesResource, loadbalancerrulesKind, c.ns, opts), &networkcontrollerv1.LoadBalancerRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &networkcontrollerv1.LoadBalancerRuleList{ListMeta: obj.(*networkcontrollerv1.LoadBalancerRuleList).ListMeta}
	for _, item := range obj.(*networkcontrollerv1.LoadBalancerRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested loadBalancerRules.
func (c *FakeLoadBalancerRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(loadbalancerrulesResource, c.ns, opts))

}

// Create takes the representation of a loadBalancerRule and creates it.  Returns the server's representation of the loadBalancerRule, and an error, if there is any.
func (c *FakeLoadBalancerRules) Create(ctx context.Context, loadBalancerRule *networkcontrollerv1.LoadBalancerRule, opts v1.CreateOptions) (result *networkcontrollerv1.LoadBalancerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(loadbalancerrulesResource, c.ns, loadBalancerRule), &networkcontrollerv1.LoadBalancerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.LoadBalancerRule), err
}

// Update takes the representation of a loadBalancerRule and updates it. Returns the server's representation of the loadBalancerRule, and an error, if there is any.
func (c *FakeLoadBalancerRules) Update(ctx context.Context, loadBalancerRule *networkcontrollerv1.LoadBalancerRule, opts v1.UpdateOptions) (result *networkcontrollerv1.LoadBalancerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(loadbalancerrulesResource, c.ns, loadBalancerRule), &networkcontrollerv1.LoadBalancerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.LoadBalancerRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLoadBalancerRules) UpdateStatus(ctx context.Context, loadBalancerRule *networkcontrollerv1.LoadBalancerRule, opts v1.UpdateOptions) (*networkcontrollerv1.LoadBalancerRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(loadbalancerrulesResource, "status", c.ns, loadBalancerRule), &networkcontrollerv1.LoadBalancerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.LoadBalancerRule), err
}

// Delete takes name of the loadBalancerRule and deletes it. Returns an error if one occurs.
func (c *FakeLoadBalancerRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(loadbalancerrulesResource, c.ns, name), &networkcontrollerv1.LoadBalancerRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLoadBalancerRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(loadbalancerrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &networkcontrollerv1.LoadBalancerRuleList{})
	return err
}

// Patch applies the patch and returns the patched loadBalancerRule.
func (c *FakeLoadBalancerRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkcontrollerv1.LoadBalancerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(loadbalancerrulesResource, c.ns, name, pt, data, subresources...), &networkcontrollerv1.LoadBalancerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.LoadBalancerRule), err
}
