/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	networkcontrollerv1 "github.com/tmax-cloud/virtualrouter/pkg/apis/networkcontroller/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNATRules implements NATRuleInterface
type FakeNATRules struct {
	Fake *FakeTmaxV1
	ns   string
}

var natrulesResource = schema.GroupVersionResource{Group: "tmax.hypercloud.com", Version: "v1", Resource: "natrules"}

var natrulesKind = schema.GroupVersionKind{Group: "tmax.hypercloud.com", Version: "v1", Kind: "NATRule"}

// Get takes name of the nATRule, and returns the corresponding nATRule object, and an error if there is any.
func (c *FakeNATRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *networkcontrollerv1.NATRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(natrulesResource, c.ns, name), &networkcontrollerv1.NATRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.NATRule), err
}

// List takes label and field selectors, and returns the list of NATRules that match those selectors.
func (c *FakeNATRules) List(ctx context.Context, opts v1.ListOptions) (result *networkcontrollerv1.NATRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(natrulesResource, natrulesKind, c.ns, opts), &networkcontrollerv1.NATRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &networkcontrollerv1.NATRuleList{ListMeta: obj.(*networkcontrollerv1.NATRuleList).ListMeta}
	for _, item := range obj.(*networkcontrollerv1.NATRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nATRules.
func (c *FakeNATRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(natrulesResource, c.ns, opts))

}

// Create takes the representation of a nATRule and creates it.  Returns the server's representation of the nATRule, and an error, if there is any.
func (c *FakeNATRules) Create(ctx context.Context, nATRule *networkcontrollerv1.NATRule, opts v1.CreateOptions) (result *networkcontrollerv1.NATRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(natrulesResource, c.ns, nATRule), &networkcontrollerv1.NATRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.NATRule), err
}

// Update takes the representation of a nATRule and updates it. Returns the server's representation of the nATRule, and an error, if there is any.
func (c *FakeNATRules) Update(ctx context.Context, nATRule *networkcontrollerv1.NATRule, opts v1.UpdateOptions) (result *networkcontrollerv1.NATRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(natrulesResource, c.ns, nATRule), &networkcontrollerv1.NATRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.NATRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNATRules) UpdateStatus(ctx context.Context, nATRule *networkcontrollerv1.NATRule, opts v1.UpdateOptions) (*networkcontrollerv1.NATRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(natrulesResource, "status", c.ns, nATRule), &networkcontrollerv1.NATRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.NATRule), err
}

// Delete takes name of the nATRule and deletes it. Returns an error if one occurs.
func (c *FakeNATRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(natrulesResource, c.ns, name), &networkcontrollerv1.NATRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNATRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(natrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &networkcontrollerv1.NATRuleList{})
	return err
}

// Patch applies the patch and returns the patched nATRule.
func (c *FakeNATRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkcontrollerv1.NATRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(natrulesResource, c.ns, name, pt, data, subresources...), &networkcontrollerv1.NATRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*networkcontrollerv1.NATRule), err
}
